### the frame config

spring.application.name: WeChatStudy
server.port: ${port:80}

spring.datasource: 
 # dev
 url: jdbc:mysql://localhost:3306/spring_auth_test?useUnicode=yes&characterEncoding=UTF8&useSSL=false
 username: root
 password: isadmin
 driver-class-name: com.mysql.jdbc.Driver



spring.jpa:
  database: MYSQL
  show-sql: false
  hibernate.ddl-auto: validate
  properties.hibernate.dialect: org.hibernate.dialect.MySQL5Dialect
  
application.wechat.official.appSecret: 7645bb79edfbc9ce4f5a3617f3fa7a14
application.wechat.official.appId: wxb6636b804967b719

application.wechat.official.token: CHZC7I8T6MAGLSXYRVFXHXENRT125478

#后台管理系统访问地址
application.system.manager.url: https://aplha.cn
