### the frame config
spring.application.name: springboot_test
server.port: ${port:8098}


spring.datasource: 
 # dev
 url: jdbc:mysql://localhost:3306/spring_test?useUnicode=yes&characterEncoding=UTF8&useSSL=false
 username: root
 password: isadmin
 driver-class-name: com.mysql.jdbc.Driver



spring.jpa:
  database: MYSQL
  show-sql: false
  hibernate.ddl-auto: validate
  properties.hibernate.dialect: org.hibernate.dialect.MySQL5Dialect

logging:
  path: ${LOG_PATH:logs}
  
spring:
  thymeleaf.prefix=classpath:/templates/
  thymeleaf.suffix=.html
  thymeleaf.mode=HTML5
  thymeleaf.encoding=UTF-8
  thymeleaf.cache=false


  
zuul:
  max:
    host:
      connections: 100
  host:
    socket-timeout-millis: ${httpRequest.callTimeout}
    connect-timeout-millis: ${httpRequest.connectTimeout}
  routes:
    MicroExpressionService:
      path: /MicroExpression/**
      url: http://127.0.0.1:8070/
      
hystrix:
    command:
        default:
            execution:
                isolation:
                    thread:
                        timeoutInMilliseconds: 60000  